namespace ArcNET.Formats;

/// <summary>
/// Script condition opcodes (SCT_* enum).
/// </summary>
public enum ScriptConditionType : byte
{
    True = 0,
    Daytime = 1,
    HasGold = 2,
    LocalFlag = 3,
    Eq = 4,
    Le = 5,
    PcQuestState = 6,
    GlobalQuestState = 7,
    ObjHasBless = 8,
    ObjHasCurse = 9,
    ObjMetPcBefore = 10,
    ObjHasBadAssociates = 11,
    ObjIsPolymorphed = 12,
    ObjIsShrunk = 13,
    ObjHasBodySpell = 14,
    ObjIsInvisible = 15,
    ObjHasMirrorImage = 16,
    ObjHasItemNamed = 17,
    ObjFollowingPc = 18,
    ObjIsMonsterOfType = 19,
    ObjIsNamed = 20,
    ObjIsWieldingItem = 21,
    ObjIsDead = 22,
    ObjHasMaxFollowers = 23,
    ObjCanOpenContainer = 24,
    ObjHasSurrendered = 25,
    ObjIsInDialog = 26,
    ObjIsSwitchedOff = 27,
    ObjCanSeeObj = 28,
    ObjCanHearObj = 29,
    ObjIsInvulnerable = 30,
    ObjIsInCombat = 31,
    ObjIsAtLocation = 32,
    ObjHasReputation = 33,
    ObjWithinRange = 34,
    ObjIsInfluencedBySpell = 35,
    ObjIsOpen = 36,
    ObjIsAnimal = 37,
    ObjIsUndead = 38,
    ObjJilted = 39,
    RumorKnown = 40,
    RumorQuelled = 41,
    ObjIsBusted = 42,
    GlobalFlag = 43,
    CanOpenPortal = 44,
    SectorIsBlocked = 45,
    MonstergenDisabled = 46,
    Identified = 47,
    KnowsSpell = 48,
    MasteredSpellCollege = 49,
    ItemsAreBeingRewielded = 50,
    Prowling = 51,
    WaitingForLeader = 52,
}
