namespace ArcNET.Formats;

/// <summary>
/// Script condition opcodes (SCT_* enum).
/// </summary>
public enum ScriptConditionType
{
    True,
    Daytime,
    HasGold,
    LocalFlag,
    Eq,
    Le,
    PcQuestState,
    GlobalQuestState,
    ObjHasBless,
    ObjHasCurse,
    ObjMetPcBefore,
    ObjHasBadAssociates,
    ObjIsPolymorphed,
    ObjIsShrunk,
    ObjHasBodySpell,
    ObjIsInvisible,
    ObjHasMirrorImage,
    ObjHasItemNamed,
    ObjFollowingPc,
    ObjIsMonsterOfType,
    ObjIsNamed,
    ObjIsWieldingItem,
    ObjIsDead,
    ObjHasMaxFollowers,
    ObjCanOpenContainer,
    ObjHasSurrendered,
    ObjIsInDialog,
    ObjIsSwitchedOff,
    ObjCanSeeObj,
    ObjCanHearObj,
    ObjIsInvulnerable,
    ObjIsInCombat,
    ObjIsAtLocation,
    ObjHasReputation,
    ObjWithinRange,
    ObjIsInfluencedBySpell,
    ObjIsOpen,
    ObjIsAnimal,
    ObjIsUndead,
    ObjJilted,
    RumorKnown,
    RumorQuelled,
    ObjIsBusted,
    GlobalFlag,
    CanOpenPortal,
    SectorIsBlocked,
    MonstergenDisabled,
    Identified,
    KnowsSpell,
    MasteredSpellCollege,
    ItemsAreBeingRewielded,
    Prowling,
    WaitingForLeader,
}
