namespace ArcNET.GameObjects;

/// <summary>NPC AI and behaviour flags.</summary>
[Flags]
public enum ObjFNpcFlags : uint
{
    /// <summary>NPC is currently fighting.</summary>
    Fighting = 1 << 0,

    /// <summary>NPC follows daytime waypoints.</summary>
    WaypointsDay = 1 << 1,

    /// <summary>NPC follows nighttime waypoints.</summary>
    WaypointsNight = 1 << 2,

    /// <summary>NPC waits at its current location.</summary>
    AiWaitHere = 1 << 3,

    /// <summary>NPC spreads out from the party.</summary>
    AiSpreadOut = 1 << 4,

    /// <summary>NPC has been jilted by the player.</summary>
    Jilted = 1 << 5,

    /// <summary>NPC checks whether it should wield an item.</summary>
    CheckWield = 1 << 6,

    /// <summary>NPC checks its weapon choice.</summary>
    CheckWeapon = 1 << 7,

    /// <summary>NPC is Kill On Sight.</summary>
    Kos = 1 << 8,

    /// <summary>NPC follows bed-time waypoints.</summary>
    WaypointsBed = 1 << 9,

    /// <summary>NPC is a forced follower.</summary>
    ForcedFollower = 1 << 10,

    /// <summary>KOS flag overridden by script.</summary>
    KosOverride = 1 << 11,

    /// <summary>NPC wanders randomly.</summary>
    Wanders = 1 << 12,

    /// <summary>NPC wanders in darkness.</summary>
    WandersInDark = 1 << 13,

    /// <summary>NPC is a fence (buys stolen goods).</summary>
    Fence = 1 << 14,

    /// <summary>NPC is a player familiar.</summary>
    Familiar = 1 << 15,

    /// <summary>NPC checks on its party leader.</summary>
    CheckLeader = 1 << 16,

    /// <summary>NPC is aloof and does not join combat automatically.</summary>
    Aloof = 1 << 17,

    /// <summary>NPC always casts its highest-level spell.</summary>
    CastHighest = 1 << 18,

    /// <summary>NPC is a generator (spawns other NPCs).</summary>
    Generator = 1 << 19,

    /// <summary>NPC was generated by a generator.</summary>
    Generated = 1 << 20,

    /// <summary>Generator rate tier 1.</summary>
    GeneratorRate1 = 1 << 21,

    /// <summary>Generator rate tier 2.</summary>
    GeneratorRate2 = 1 << 22,

    /// <summary>Generator rate tier 3.</summary>
    GeneratorRate3 = 1 << 23,

    /// <summary>NPC removes maintained spells when resting.</summary>
    DemaintainSpells = 1 << 24,

    /// <summary>NPC looks for a weapon to pick up.</summary>
    LookForWeapon = 1 << 25,

    /// <summary>NPC looks for armor to equip.</summary>
    LookForArmor = 1 << 26,

    /// <summary>NPC looks for ammunition.</summary>
    LookForAmmo = 1 << 27,

    /// <summary>NPC is backing away from an enemy.</summary>
    BackingOff = 1 << 28,

    /// <summary>NPC will not initiate attacks.</summary>
    NoAttack = 1 << 29,
}
