namespace ArcNET.GameObjects;

/// <summary>NPC AI and behaviour flags.</summary>
[Flags]
public enum ObjFNpcFlags : uint
{
    /// <summary>No flags set.</summary>
    None = 0,

    /// <summary>NPC is currently fighting.</summary>
    Fighting = 0x1,

    /// <summary>NPC follows daytime waypoints.</summary>
    WaypointsDay = 0x2,

    /// <summary>NPC follows nighttime waypoints.</summary>
    WaypointsNight = 0x4,

    /// <summary>NPC waits at its current location.</summary>
    AiWaitHere = 0x8,

    /// <summary>NPC spreads out from the party.</summary>
    AiSpreadOut = 0x10,

    /// <summary>NPC has been jilted by the player.</summary>
    Jilted = 0x20,

    /// <summary>NPC checks whether it should wield an item.</summary>
    CheckWield = 0x40,

    /// <summary>NPC checks its weapon choice.</summary>
    CheckWeapon = 0x80,

    /// <summary>NPC is Kill On Sight.</summary>
    Kos = 0x100,

    /// <summary>NPC follows bed-time waypoints.</summary>
    WaypointsBed = 0x200,

    /// <summary>NPC is a forced follower.</summary>
    ForcedFollower = 0x400,

    /// <summary>KOS flag overridden by script.</summary>
    KosOverride = 0x800,

    /// <summary>NPC wanders randomly.</summary>
    Wanders = 0x1000,

    /// <summary>NPC wanders in darkness.</summary>
    WandersInDark = 0x2000,

    /// <summary>NPC is a fence (buys stolen goods).</summary>
    Fence = 0x4000,

    /// <summary>NPC is a player familiar.</summary>
    Familiar = 0x8000,

    /// <summary>NPC checks on its party leader.</summary>
    CheckLeader = 0x10000,

    /// <summary>NPC is aloof and does not join combat automatically.</summary>
    Aloof = 0x20000,

    /// <summary>NPC always casts its highest-level spell.</summary>
    CastHighest = 0x40000,

    /// <summary>NPC is a generator (spawns other NPCs).</summary>
    Generator = 0x80000,

    /// <summary>NPC was generated by a generator.</summary>
    Generated = 0x100000,

    /// <summary>Generator rate tier 1.</summary>
    GeneratorRate1 = 0x200000,

    /// <summary>Generator rate tier 2.</summary>
    GeneratorRate2 = 0x400000,

    /// <summary>Generator rate tier 3.</summary>
    GeneratorRate3 = 0x800000,

    /// <summary>NPC removes maintained spells when resting.</summary>
    DemaintainSpells = 0x1000000,

    /// <summary>NPC looks for a weapon to pick up.</summary>
    LookForWeapon = 0x2000000,

    /// <summary>NPC looks for armor to equip.</summary>
    LookForArmor = 0x4000000,

    /// <summary>NPC looks for ammunition.</summary>
    LookForAmmo = 0x8000000,

    /// <summary>NPC is backing away from an enemy.</summary>
    BackingOff = 0x10000000,

    /// <summary>NPC will not initiate attacks.</summary>
    NoAttack = 0x20000000,
}
